name: deskpower
description: An app to power my desktop on from anywhere

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  http: ^0.13.5
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon-1024x1024.png"
  adaptive_icon_foreground: "assets/images/adaptive-icon-900x900.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: false
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/images/icon-foreground-1024x1024.png"
  android_12:
    image: "assets/images/splash-1152x1152.png"
    color: "#FFFFFF"
    color_dark: "#000000"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
